### ISSUE TITLE
parent registration

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#10]
followed the email link (manual type in of the website address...!)

on an iphone 6, couldn't paste the password into the box, had to be manually typed in.

Once I overcame that; I pretended to be Becks (to make things clearer in the system....), but I haven't entered James name yet either as coach or parent.....will be linked to my other bug thing to be sent...

**Comment by juur** [comment]
**Enhancement**: replace temporary password with invitation email that triggers a "type in new password" instead of "copy/paste password"

**Comment by juur** [comment]
This is done, but might need testing.
You can now be authenticated via the verification email, if you have a blank password. You are given temporary access and forced to the profile page until your password (and any other missing information) is provided.

#26 really needs to be done now.
