### ISSUE TITLE
adding score didn't work

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#18]
![image](https://user-images.githubusercontent.com/44071147/46835343-d0bac880-cda5-11e8-9c26-489e96545b55.png)

**Comment by juur** [comment]
I think i've fixed this. Typo on the code mixing active and old matches up.

**Comment by juur** [comment]
I've now figured out what is causing this category of bug (and the misreporting of it in the UI)
Have opened #25 to track this.
