### ISSUE TITLE
coach dashboard bringing in teams I am playing against

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#19]
should only be 'my' team....

![image](https://user-images.githubusercontent.com/44071147/46835413-052e8480-cda6-11e8-8da7-5ee67b2901e5.png)

**Comment by juur** [comment]
@jonodennis1 Ah OK. I think I know what is happening here - did you populate the email address of the coach from the other club, or just the club's name ?
IF you don't provide an email for them, you are the owner, until you invoke the 'transfer club' feature.

**Comment by jonodennis1** [comment]
OK - we probably need a better parking area to dump the teams, because "I" (wearing my team manager hat) don't care about Oakley green per se....I just have added them to keep my admin clean....

**Comment by juur** [comment]
The database has a concept of a club being in a caretaker mode, so I should just show them separately that then solves the confusion.
