### ISSUE TITLE
user Registration cycle

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#3]
- having registered, and clicked ok...it has sent me back to the screen saying log in....surely it should leave you logged in, or take you to a verification page?

- As I have an old password stored, clicking login with the old combo results in nothing...think there should be an error message

- Font look tiny on my screen...... you can't see all of the email address box to know if you have typed it in incorrectly

**Comment by juur** [comment]
Have created #4 to cover your 2nd point

**Comment by juur** [comment]
Can you provide a screenshot for your 3rd one? I have tested on my PC and my phone and it looks ok.

**Comment by jonodennis1** [comment]
#dickhead

 

Did cntrl and 0 to get it to ‘normal’ and it looks fine….I must have had it zoomed out for some reason!!  Scratch that one from the record!!

 

Jon Dennis

078 0378 2100

**Comment by juur** [comment]
Created #8 to cover your 1st point and closing this
