### ISSUE TITLE
parent invite page

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#38]
https://mypty.uk/team-management.shtml

the bulk load is the dogs bollocks!!! Brilliant!!

we have two grids - parents and kids - would it make more sense to have them as one grid, as we will have a list of c20 names twice otherwise.

The second thing is there is no way of seeing if the parents have completed the registration process - could we have a green tick or something.  Do we need to have a button to 'self serve' a repeat email?

**Comment by juur** [comment]
I've added a basic "signup step" display for parents (NONE = all done) I'll tidy the visuals up later.
Repeated parent names i've done for now, having to parse a more complex structured CSV is quite a bit of effort (and a lot of error handling for people putting blank columns/rows/blah in)
