### ISSUE TITLE
match set up issues

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#41]
https://mypty.uk/match-management.shtml

1. There is a random 40!

![image](https://user-images.githubusercontent.com/44071147/48583794-fb0d2200-e91f-11e8-9aeb-b1be7746560c.png)

2.  I entered the score (2 nil win).... but it appears to have disappeared!  Its neither in the visible table, nor when you click the button

![image](https://user-images.githubusercontent.com/44071147/48583853-1ed06800-e920-11e8-9ff5-cd57d110c8e1.png)

3. The votes button doesn't seem to do anything!

**Comment by juur** [comment]
The 40 is not random, it is the unique id for the match (but probably not relevant).. the rest, will check

**Comment by juur** [comment]
There was a problem with having a score of 0 being the same as not providing a score, this is fixed.
I can't replicate your other issue (maybe related?)

**Comment by juur** [comment]
Closing as assuming fixed.
