### ISSUE TITLE
Notify parents that voting is now open

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#42]
how do we get to the voting bit to kick off?

**Comment by juur** [comment]
that is a very good point i haven't actually written the spam-parents-they-can-vote-now!

**Comment by juur** [comment]
@jonodennis1 this is on the list now :-)

**Comment by juur** [comment]
There is now a 'Send Vote Email' button on the Matches screen, in the 'Ready to Vote' list. It is disabled if notification has already been sent.
