### ISSUE TITLE
club registration issues

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#48]
https://mypty.uk/club-registration.shtml

the list of sports didn't load, so its all grayed out..
'Correspondence' is spelt incorrectly
Under the org status, we should probably remove the word 'football' as it wouldn't make sense if other sports enroll

**Comment by juur** [comment]
I renamed something from 'entries' to 'list' and broke the world :-(
This should mostly be fixed. And the typo.
I've made #49 for the last part.
