### ISSUE TITLE
Club registration

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#5]
#1 for the club name, can we have it start to auto populate from the database of names to minimise the number permutations for the same club, which would auto select the the sport, name etc

#2 Can we make it clear that its the manager address...

**Comment by juur** [comment]
Using # 1 gets interpreted as a link to an actual existing bug ;-) you're better using 1. 2. 3. instead

**Comment by jonodennis1** [comment]
1.	Roger that!

 

I have to have a chat with New Zealand tonight, so should get a good way through this.  Quick observation – fucking brilliant and you’ve done a excellent job on this!!

 

Jon Dennis

078 0378 2100

**Comment by juur** [comment]
BTW if you reply with email, it posts your phone number on the Internet for everyone to read :-)
Have to pay money to keep this 'private'

**Comment by juur** [comment]
Have fixed 2 - it should be the registered address of the Club
Not sure how we'd do 1 - each Club should only be registered once, then each Team ("Under 12s") gets created underneath.
