### ISSUE TITLE
Explain the voting options

### ISSUE THREAD

**Issue by jonodennis1** [mypoty/poty-issues#7]
Can we have an "i" that you hoover which explains the voting options......

![image](https://user-images.githubusercontent.com/44071147/46832236-70278d80-cd9d-11e8-936e-9ee60f997cfa.png)

**Comment by jonodennis1** [comment]
Also, we'd never vote for the opposition !  You can kill that feature!!!

**Comment by juur** [comment]
Tidied up the team page into tabs with a description of the voting types.
